/* auto-generated by NAPI-RS */
/* eslint-disable */
/** An active subscription that can be unsubscribed */
export declare class Subscription {
  /** Stop watching for file system changes */
  unsubscribe(): void;
}

/**
 * Subscribe to file system changes in a directory
 *
 * # Arguments
 * * `directory` - The directory path to watch
 * * `callback` - Function called with (error, events) when changes occur
 * * `options` - Optional configuration including ignore patterns
 *
 * # Returns
 * A subscription that can be used to stop watching
 */
export declare function subscribe(directory: string, callback: (result: WatchCallbackResult) => void, options?: WatchOptions): Subscription;

/** Callback result type for the watcher */
export interface WatchCallbackResult {
  error?: Error;
  events: Array<WatchEvent>;
}

/** A file system event */
export interface WatchEvent {
  path: string;
  type: 'create' | 'update' | 'delete';
}

/** Options for configuring the watcher */
export interface WatchOptions {
  /** Patterns to ignore (file paths or glob patterns) */
  ignore?: Array<string>;
}
